spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

app:
  datasource:
    superadmin:
      url: jdbc:postgresql://localhost:5432/super_admin_db
      username: postgres
      password: Akef123*
      driver-class-name: org.postgresql.Driver

    erp:
      url: jdbc:postgresql://localhost:5432/erp_mt_db
      username: postgres
      password: Akef123*
      driver-class-name: org.postgresql.Driver

    dw:
      url: jdbc:postgresql://localhost:5432/dw_db
      username: postgres
      password: Akef123*
      driver-class-name: org.postgresql.Driver