spring:
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false

app:
  datasource:
    erp:
      url: jdbc:postgresql://49.13.75.18:5432/rest_erp
      username: readonly_user
      password: strong_password

    dw:
      url: jdbc:postgresql://localhost:5432/rest_erp_dw
      username: postgres
      password: Messaoud123!